-- =============================================================================
-- MediDispense AWS RDS Schema
-- Run this to (re)create the database from scratch.
-- Safe to run on a fresh RDS instance.
-- =============================================================================

-- Drop everything in dependency order
DROP TABLE IF EXISTS dispensing_logs    CASCADE;
DROP TABLE IF EXISTS slot_medications   CASCADE;
DROP TABLE IF EXISTS medication_schedules CASCADE;
DROP TABLE IF EXISTS medications        CASCADE;
DROP TABLE IF EXISTS slot_bindings      CASCADE;
DROP TABLE IF EXISTS patients           CASCADE;
DROP TABLE IF EXISTS users              CASCADE;

-- =============================================================================
-- patients
--   Source of truth lives on the Pi.
--   patient_id is a TEXT UUID generated by the Pi (not gen_random_uuid()).
-- =============================================================================
CREATE TABLE patients (
    patient_id      VARCHAR(255) PRIMARY KEY,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    date_of_birth   TEXT,
    deleted_at      TEXT,
    cloud_synced_at TEXT,
    created_at      TEXT
);

-- =============================================================================
-- medications
--   Each medication belongs to one patient.
--   No FK to patients — Pi may push medications before patients are synced.
-- =============================================================================
CREATE TABLE medications (
    medication_id       VARCHAR(255) PRIMARY KEY,
    patient_id          VARCHAR(255) NOT NULL,
    medication_name     VARCHAR(200) NOT NULL,
    pill_barcode        VARCHAR(100),
    pill_color_shape    VARCHAR(100),
    remaining_count     INTEGER      DEFAULT 0,
    low_stock_threshold INTEGER      DEFAULT 5,
    expiry_date         TEXT,
    created_at          TEXT,
    cloud_synced_at     TEXT
);

-- =============================================================================
-- medication_schedules
--   Slot-centric architecture: a schedule belongs to a patient + slot.
--   medication_id is intentionally NULL (legacy column kept for compat only).
--   No NOT NULL constraints that would block Pi pushes.
-- =============================================================================
CREATE TABLE medication_schedules (
    schedule_id    VARCHAR(255) PRIMARY KEY,
    patient_id     VARCHAR(255),
    slot_id        INTEGER,
    medication_id  VARCHAR(255),          -- nullable, legacy — not used by Pi
    planned_time   TEXT         NOT NULL,  -- HH:MM
    is_active      BOOLEAN      DEFAULT TRUE,
    start_date     TEXT,
    end_date       TEXT,
    frequency_type TEXT         DEFAULT 'daily',
    week_days      TEXT         DEFAULT '',
    window_seconds INTEGER      DEFAULT 300,
    group_id       VARCHAR(255),
    dosage_quantity INTEGER     DEFAULT 1  -- legacy, kept for compat
);

-- =============================================================================
-- slot_bindings
--   Maps physical slot → patient. Mirrors Pi's slot_bindings table.
-- =============================================================================
CREATE TABLE slot_bindings (
    slot_id    INTEGER      PRIMARY KEY,
    patient_id VARCHAR(255),
    status     VARCHAR(50)  DEFAULT 'empty',
    updated_at TEXT
);

-- =============================================================================
-- slot_medications
--   Medications physically loaded into a slot.
--   Mirrors Pi's slot_medications table.
-- =============================================================================
CREATE TABLE slot_medications (
    id              SERIAL       PRIMARY KEY,
    slot_id         INTEGER      NOT NULL,
    patient_id      VARCHAR(255),
    medication_id   VARCHAR(255) NOT NULL,
    medication_name TEXT,
    barcode         TEXT,
    target_count    INTEGER      DEFAULT 1,
    loaded_count    INTEGER      DEFAULT 0,
    updated_at      TEXT
);

-- =============================================================================
-- dispensing_logs
--   Pushed from Pi's sync_queue table after each dispense event.
-- =============================================================================
CREATE TABLE dispensing_logs (
    log_id           VARCHAR(255) PRIMARY KEY,
    patient_id       VARCHAR(255) NOT NULL,
    schedule_id      VARCHAR(255),
    status           VARCHAR(50)  NOT NULL,   -- 'dispensed', 'taken', 'missed', 'error'
    face_auth_score  FLOAT,
    dispensing_at    TEXT,
    taken_at         TEXT,
    device_timestamp TEXT,
    error_details    TEXT
);

-- =============================================================================
-- users
--   App accounts (caregivers / patients with login).
-- =============================================================================
CREATE TABLE users (
    id              SERIAL       PRIMARY KEY,
    email           VARCHAR(255) UNIQUE NOT NULL,
    password_hash   TEXT         NOT NULL,
    role            VARCHAR(50)  NOT NULL DEFAULT 'patient',
    patient_id      VARCHAR(255),
    created_at      TEXT,
    cloud_synced_at TEXT
);

-- =============================================================================
-- Indexes for common queries
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_medications_patient     ON medications (patient_id);
CREATE INDEX IF NOT EXISTS idx_schedules_patient       ON medication_schedules (patient_id);
CREATE INDEX IF NOT EXISTS idx_schedules_slot          ON medication_schedules (slot_id);
CREATE INDEX IF NOT EXISTS idx_schedules_group         ON medication_schedules (group_id);
CREATE INDEX IF NOT EXISTS idx_slot_meds_slot          ON slot_medications (slot_id);
CREATE INDEX IF NOT EXISTS idx_dispensing_logs_patient ON dispensing_logs (patient_id);
CREATE INDEX IF NOT EXISTS idx_dispensing_logs_sched   ON dispensing_logs (schedule_id);
CREATE INDEX IF NOT EXISTS idx_patients_deleted        ON patients (deleted_at);
